title: Bernardo Guerreiro
email: saveknut@gmail.com
description: >-
  Lorem ipsum dolor sit amet.
baseurl: "" # e.g. /blog
url: "saveknut.github.io" # e.g. http://example.com
twitter_username: saveknut
github_username:  saveknut

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
